### ISSUE TITLE
Remove bottom bit from course search altogether

### ISSUE THREAD

**Issue by kimberleydejong** [kimberleydejong/iec#18]
![image](https://cloud.githubusercontent.com/assets/25530241/22642100/35d0cacc-ec51-11e6-9379-a7dc7ff0ab72.png)

**Comment by Designershree** [comment]
![screenshot from 2017-02-13 17-00-36](https://cloud.githubusercontent.com/assets/25296332/22881784/0d764ed6-f20e-11e6-8dac-d42e98631d99.png)

Please check this..As i cannot see the section you want to remove because i have already it.

Thanks.

**Comment by kimberleydejong** [comment]
![image](https://cloud.githubusercontent.com/assets/25530241/22969777/a49b10f8-f367-11e6-8de8-505aaf83596d.png)

Could you make sure that the image stretches all the way to the bottom so that there's no white gap?
