### ISSUE TITLE
Menu "Contact US" divided 

### ISSUE THREAD

**Issue by BothOfUs** [kimberleydejong/iec#31]
**Tested on :** Mac 10.12.2 , Chrome 55.0

**Steps to recreate **
1) Navigate to website and look into menu 

**Current behaviour :**
The "Contact us" in menu is divided into Contact in one line and us in different line.

**Expected behaviour:**
The menu "Contact us" to be in same line.

**Screenshot :**
![image](https://cloud.githubusercontent.com/assets/24927857/22766064/bf7d1e14-ee73-11e6-8763-9c4567bdfb9d.png)

**Comment by kimberleydejong** [comment]
It's still not showing up right for me, can we try a smaller font size?

**Comment by kimberleydejong** [comment]
![image](https://cloud.githubusercontent.com/assets/25530241/22969689/51d21cf4-f367-11e6-9121-cda65fc87130.png)

Still the case :( have you tried a smaller font size? 

If nothing works, could we maybe try to make 'Apply online' into a button and moving it next to the flags (on the right hand side)
